// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oquueaslgrnfkkifxvhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdXVlYXNsZ3JuZmtraWZ4dmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODg2OTUsImV4cCI6MjA1ODE2NDY5NX0.H9ti6BwWy8r9PPbFFmIm9f44RYDczhn5J1KD-dlzYNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);